---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acct-mgt-deployment
spec:
  template:
    spec:
      containers:
        - name: acct-mgt
          image: larsks/acct-mgt:be985a61a406b8cdce5d8c840bfc248c1c4abbef
          imagePullPolicy: IfNotPresent
